### ISSUE TITLE
Events not fired with MyHomeServer1

### ISSUE THREAD

**Issue by alessandro-lac** [anotherjulien/MyHOME#3]
Hi, 
as mentioned in another issue ([link](https://github.com/anotherjulien/MyHOME/issues/2)) events (all of them) are not fired in my setup. I can control lights and thermostats, but when I press buttons no event is fired in my home assistant. 

![image](https://user-images.githubusercontent.com/1499430/101260497-b20bae80-3730-11eb-96a3-f0806e2ac634.png)

Am I doing something wrong?
Any suggestion?

(I tried with version 0.7.1)

**Comment by anotherjulien** [comment]
Do you have correct status feedback for all other entities? (for example, if you use a wall switch to turn a light on, does it show on Home Assistant?)

Are you positive the events you are trying to see are indeed generated? Do you see them with an OpenWebNet client for instance?
(I'm asking because just today I reprogrammed a wall switch for CEN+, and it unexplainably did not work if one of the configured pushbutton was 0. It just did not send the CEN+ messages on the bus at all)

**Comment by alessandro-lac** [comment]
If I do turn a light on its status shows correctly into home assistant, the same happens if I turn off the same light, it does turn off and the physical button switches from purple to blue. 

I don't know how to check the second question, if I open the OpenWebNet client and push a button this is what I see: 
![image](https://user-images.githubusercontent.com/1499430/101262291-c99d6400-373d-11eb-9b04-8b59dba59fdc.png)

Is it correct?

**Comment by anotherjulien** [comment]
Yes, good. So this is what you see when you press the button to turn off the light A=2 PL=8.
Now what do you see when you press a CEN or CEN+ button?

**Comment by alessandro-lac** [comment]
This is what happens when I press an OFF button
![image](https://user-images.githubusercontent.com/1499430/101278137-b0d29400-37b9-11eb-88c5-db7c85b1d3ea.png)

**Comment by anotherjulien** [comment]
You are trying to use CEN and/or CEN+ events, correct?
So can you show me what happens when you press a wall switch that is configured to trigger a CEN or a CEN+ message?

**Comment by alessandro-lac** [comment]
Sorry, maybe I am understanding it wrong: I thought that every button switching off multiple lights should use a CEN/CEN+ message. Is this right? 

That is why I posted the messages of a general OFF button which I have nearby the entry door. Sorry, but I am not very into BTicino configuration...

**Comment by anotherjulien** [comment]
No, a button switching multiple lights is not a CEN button.
A button configured as "general" will control all lights, and a button configured for an area will control all lights within the area.
Each of these two generate events in the integration: `myhome_general_light_event` and `myhome_area_light_event` respectively.
But if you are simply trying to have a status feedback in Home Assistant when using a GEN command, this should work out of the box starting with the integration in version 0.7.1.

**Comment by alessandro-lac** [comment]
So, just to wrap my head around it: 
if a button control multiple lights it should at least send one of the following events: `myhome_general_light_event ` `myhome_area_light_event `. 

If I listen, from the developer tools to those events, they never get triggered in my HA (tried both with 0.7.1 and 0.7.2). I don't know, is it possible that my electrician configured the buttons with other types of configurations?

**Comment by anotherjulien** [comment]
Yes, it is possible.
Maybe all your lights are in the same group and what is sent is a group command?
Or maybe this has been done with a scenario?
If the last screenshot you sent is absolutely all you can see when you press the button, then I do not know because this is just individual commands (and one group command `*1*0*#6##`
It's probably best to first identify how your button is configured and go from there.
