### ISSUE TITLE
Cover: lateral openings instead of vertical

### ISSUE THREAD

**Issue by Fedo-be** [anotherjulien/MyHOME#39]
In short: 
![image](https://user-images.githubusercontent.com/35451617/147854445-991d6bb1-cd31-4fb0-bdb2-ed6129af2ec4.png)
Hello,
I managed to control the covers, but I also have a curtain which opens sideways.
The same topic is covered in one of the many Home Assistant community pages, but the device class is not recognized.
Is it possible to have this possibility in the current version?
Maybe I missed something, but I think I checked the necessary code to check if this option was not hidden somewhere, but then again, I've been wrong before. ;-)
Thank you for your help.

**Comment by anotherjulien** [comment]
I've now made use of the new enum system for `device_class` since fddf73bdac475fa6de4638f46a5f50fb93c12029.
This allows to change the device class of supported entities using the "Show as" drop down list in the GUI.
At the moment HA does not seem to support this (correctly) for covers but I can only hope it will soon.

Since this is something that will soon come from core, I'm not going to implement anything specific to allow it in the integration at this point.
